server {
    # Nginx Container 내부 TCP 80에서 요청 대기
    listen 80;

    server_name _;

    location / {
        # Compose Service Name 'app'
        # App Container 내부 TCP 5000으로 전달
        proxy_pass http://app:5000;

        # 원래 요청 Host 정보 전달
        proxy_set_header Host $host;

        # Client 실제 IP 정보 전달
        proxy_set_header X-Real-IP $remote_addr;

        # Proxy 경로를 거친 Client IP Chain 전달
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}